# Generated by Django 2.0.6 on 2018-06-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('opens_at', models.TimeField(default='08:00:00')),
                ('closes_at', models.TimeField(default='23:59:59')),
            ],
        ),
    ]
